### ISSUE TITLE
i will sue you for stealing something in the readme

### ISSUE THREAD

**Issue by hellory4n** [brycked/hmues.js#1]
Hi, I'm Martin Magnet, CEO of Funcade Super Corporation Incorporated. Please remove the stolen thing. Or I will sue you.

Cheers,
Martin Magnet

**Comment by hellory4n** [comment]
### h
**B**
_I_

> ok
`<>`
[link icon](https://example.com)

- the
- the
- the

1. the
2. the

- [ ] the
- [x] the

@hellory4n

**Comment by bricked-dev** [comment]
didnt ask :>

**Comment by hellory4n** [comment]
![image](https://user-images.githubusercontent.com/95989937/192892045-fbbf9dcb-2519-4a46-a29c-e4cc2ffaecfd.png)

**Comment by bricked-dev** [comment]
you made open source so i can steal 🥰

**Comment by bricked-dev** [comment]
dis is now my property

**Comment by hellory4n** [comment]
fudge i should've made everything absolutely proprietary

**Comment by bricked-dev** [comment]
better save it on cloud next time 🤓
